# 2.18

import turtle
t = turtle.Turtle()
t.speed(5)
def yingyang(raio):
    t.width(5)
    t.left(90)
    t.fillcolor('black')
    t.begin_fill()
    t.circle(raio, extent=180)
    t.circle(2*raio, extent=180)
    t.end_fill()
    t.circle(2*raio, extent=180)
    t.penup()
    t.goto(0, 0)
    t.pendown()
    t.width(0)
    t.fillcolor('white')
    t.begin_fill()
    t.circle(raio, extent=180)
    t.end_fill()
    t.penup()
    t.width(5)
    t.goto((raio/2)+80, 0)
    t.pendown()
    t.fillcolor('black')
    t.begin_fill()
    t.circle(30)
    t.end_fill()
    t.penup()
    t.width(0)
    t.goto(-raio+30, 0)
    t.pendown()
    t.fillcolor('white')
    t.begin_fill()
    t.circle(30)
    t.end_fill()
    
if __name__ == '__main__':
    yingyang(100)
    t.exitonclick()